services:
  db:
    image: opensearchproject/opensearch:2.12.0
    container_name: db
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - db-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - local-env-net
    dns:
      - 10.0.1.3

  db-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: db-dashboards
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    ports:
      - 5601
    networks:
      - local-env-net
    dns:
      - 10.0.1.3
    depends_on:
      - db

  localstack:
    container_name: "localstack"
    image: localstack/localstack:stable
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # External services port range
    environment:
      - DEBUG=${LOCALSTACK_DEBUG:-0}
      - LOCALSTACK_HOST=${LOCALSTACK_HOST}
      - OPENSEARCH_CUSTOM_BACKEND=${OPENSEARCH_HOSTS}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    volumes:
      - ./services/localstack/init/ready.d:/etc/localstack/init/ready.d
      - ./services/localstack/services:/opt/code/localstack/services
      - ./services/localstack/volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-env-net
    dns:
      - 10.0.1.3
    depends_on:
      - db

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - 61616   # ActiveMQ protocol
      - 8161    # Admin Console
    networks:
      - local-env-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181
    networks:
      - local-env-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka.local-env.com:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092
    networks:
      local-env-net:
        aliases:
          - kafka.local-env.com
    depends_on:
      - zookeeper

  kafka-dashboards:
    image: obsidiandynamics/kafdrop
    container_name: kafka-dashboards
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    ports:
      - 9000
    networks:
      - local-env-net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./services/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/etc/nginx/conf.d/http:/etc/nginx/conf.d/http
      - ./services/nginx/etc/nginx/conf.d/stream:/etc/nginx/conf.d/stream
      - ./services/minica/app/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
      - "9092:9092"
      - "61617:61617"
    networks:
      local-env-net:
        ipv4_address: 10.0.1.2
    depends_on:
      - bind
      - minica
      - db
      - db-dashboards
      - localstack
      - activemq
      - kafka
      - kafka-dashboards

  bind:
    build: services/bind
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./services/bind/named.conf:/etc/bind/named.conf
      - ./services/bind/zones:/etc/bind/zones
    restart: always
    networks:
      local-env-net:
        ipv4_address: 10.0.1.3

  minica:
    build: services/minica
    container_name: minica
    environment:
      - LOCALSTACK_HOST=${LOCALSTACK_HOST}
    volumes:
      - ./services/minica/app:/app
      - ./services/nginx/etc/nginx/conf.d:/etc/nginx/conf.d

volumes:
  db-data:
    name: db-data
    driver: local

networks:
  local-env-net:
    name: local-env-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
          ip_range: 10.0.1.64/26
